// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhfMko0VUnkLZrjF5yWzkmdxu3dbIkU4',
    appId: '1:180539795026:web:788ded26335fc5a6e2618b',
    messagingSenderId: '180539795026',
    projectId: 'pisyadmin-dd337',
    authDomain: 'pisyadmin-dd337.firebaseapp.com',
    storageBucket: 'pisyadmin-dd337.appspot.com',
    measurementId: 'G-HNJ9GRHZKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TaqZvX4E-_elF8_87W91GiMp0Q2x60g',
    appId: '1:180539795026:android:856c791e54d9f958e2618b',
    messagingSenderId: '180539795026',
    projectId: 'pisyadmin-dd337',
    storageBucket: 'pisyadmin-dd337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNzxZwNk0cZ8_j9DawqB_-RpsKWK3Guc',
    appId: '1:180539795026:ios:2727259da71f53a7e2618b',
    messagingSenderId: '180539795026',
    projectId: 'pisyadmin-dd337',
    storageBucket: 'pisyadmin-dd337.appspot.com',
    iosBundleId: 'com.example.pisyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUNzxZwNk0cZ8_j9DawqB_-RpsKWK3Guc',
    appId: '1:180539795026:ios:2727259da71f53a7e2618b',
    messagingSenderId: '180539795026',
    projectId: 'pisyadmin-dd337',
    storageBucket: 'pisyadmin-dd337.appspot.com',
    iosBundleId: 'com.example.pisyadmin',
  );
}
